gems: [jekyll-paginate]

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            ProLaLa
tagline:          'Programming Languages for the Law'
description:      'Programming Languages for the Law'
url:              https://prolala.github.io/
baseurl:          /prolala/

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
